Light Distribution Proposal
mvrdevelopment/spec pull request #183
Opened 2024-03-14 12:43 UTC by moritzstaffel

2024-04-17 11:50 UTC, moritzstaffel commented
We need to discuss this tomorrow in our meeting

2024-04-18 09:52 UTC, moritzstaffel commented
I have updated the definition to the latest discussion we had.

What is missing is:
- What are we doing about the measurement procedure? Do we want to add some information on how this is done?

2024-05-16 12:03 UTC, AndriiVoitenko requested changes

2024-05-22 08:47 UTC, moritzstaffel commented on gdtf-spec.md
> +| LightDistribution              | [Resource](#user-content-attrtype-resource )     | Optional. File name without extension and without subfolder containing description of the IES or EULUMDAT file in
This feature is similar like the model overwrite that we defined for Geometry References.

Use case it the following: You have multiple pixels that will be controlled all the same way, but have different geometry that you want to display. Good example are the multi LED devices from robe. [Link to Share](https://gdtf-share.com/share.php?page=home&manu=Robe%20Lighting&fix=Robin%20iSpiider&rev=53150)

| Lens 1  | Lens 2  |
|---|---|
| ![Bildschirmfoto 2024-05-22 um 10 38 34](https://github.com/mvrdevelopment/spec/assets/13522639/0b13d5c2-d220-4d11-a448-0bbcbc233acb)  |  ![Bildschirmfoto 2024-05-22 um 10 38 37](https://github.com/mvrdevelopment/spec/assets/13522639/70cbb07a-1e02-4dfc-b7b2-e4a42b3af36e) |


When now bringing the Light Distribution in here, this seems like a good thing to also enable, as it reduces the amount of duplication that you need.

2024-05-22 08:47 UTC, moritzstaffel commented on gdtf-spec.md
> +| LightDistributionFrom         | [Resource](#user-content-attrtype-resource )         | Optional. IES or LDT file name without extension containing the spectral data for the start of this range. |
This is part of the old proposal. I have not updated it. 
But the main idea to have LightDistribution attributes in the ChannelFunction and in something below of the Channel Functions is that there could be multiple beams with different LightDistribution. So basically you need an array of LightDistribution to define the output. 
How we do it is currently not decided, but is on the list for tomorrows meeting

2024-05-22 08:47 UTC, moritzstaffel commented on gdtf-spec.md
> +| Beam         | [Name](#user-content-attrtype-name )         | Optional link to the Beam Geometry this is for |
When it is in the channel function, LightDistribution is considered to be for all beams. (Normally when you assign it like this, there will be only one beam) When you use the other way, you can define the beam that will be defined. (Normally this is for fixtures that have different beam types like LED fixtures.)

2024-05-22 14:27 UTC, AndriiVoitenko commented on gdtf-spec.md
> +| LightDistribution              | [Resource](#user-content-attrtype-resource )     | Optional. File name without extension and without subfolder containing description of the IES or EULUMDAT file in
And model overwrite is a new feature. We have splited controling and physical settings, therefore "controlled in the same way" should not be a valid argument here, but ok you are right, if we already starts with this rabbit hole, then we need to be consistent and another overwrite looks plausible.

2024-05-23 07:22 UTC, petrvanekrobe commented on gdtf-spec.md
> +| LightDistribution     | [Resource](#user-content-attrtype-resource )     | Optional. File name without extension and without subfolder containing description of the IES or EULUMDAT file in the subf
We should not be inventing new "LightDistribution" terminology, which only describes part of what Photometric Data is and also seems to be [used for other purposes](https://www.agcled.com/blog/what-is-light-distribution-type-i-type-ii-type-iii-type-iv-type-v.html). What we want to define is **PhotometricData**:

- EULUMDAT is a data [file format](https://en.wikipedia.org/wiki/File_format) used for specification of [photometric](https://en.wikipedia.org/wiki/Photometry_(optics)) data especially [intensity](https://en.wikipedia.org/wiki/Luminous_intensity) distributions from light sources such as lamps and luminaries.
- IES [Standard File Format](https://store.ies.org/product/lm-63-19-approved-method-ies-standard-file-format-for-the-electronic-transfer-of-photometric-data-and-related-information/?v=928568b84963) for the Electronic Transfer of Photometric Data and Related Information.

2024-05-23 07:28 UTC, moritzstaffel commented on gdtf-spec.md
> +| LightDistribution     | [Resource](#user-content-attrtype-resource )     | Optional. File name without extension and without subfolder containing description of the IES or EULUMDAT file in the subf
So rename **LightDistribution** to **PhotometricData**? That sounds reasonable

2024-05-23 07:35 UTC, petrvanekrobe commented on proposal/light-distribution-proposal/proposal.md
> +    - Multi LED Strip Light (Challenge is how you measure device)
If you can control a single pixel, the Photometric Data must be for that pixel. This is done by the data provider (device manufacturer) by taking the overall photometric measurement of the whole device and diving it, to provide data only for that particular pixel.

2024-05-23 14:28 UTC, AndriiVoitenko commented on gdtf-spec.md
> +| LightDistributionFrom         | [Resource](#user-content-attrtype-resource )         | Optional. IES or LDT file name without extension containing the spectral data for the start of this range. |
Maybe as suggestion: 

1. define new enum value for sub physical unit Type "PhotometricData". Define new enum value for PhysicalUnit "IEC" and maybe as additional for the future "EULUMDAT". 
2. all attributes, which can change light distribution like zoom will get a new sub physical with those defined new values (Annex B)
3. Beam get a new Property PhotometricData with file name
4. Sub channel set get only a new property Beam
5. All physical From and To (in channel function, channel sets, attributes...) will be changed to string. And the meaning of string will be defined in Attribute or in sub physical in case of sub channel set. There for for sub channel set linked to sub physical with Type "PhotometricData" Physical From/To should contain IES or EULUMDAT file name depending on PhysicalUnit of sub physical.

2024-05-29 09:18 UTC, moritzstaffel commented on gdtf-spec.md
> +| LightDistribution     | [Resource](#user-content-attrtype-resource )     | Optional. File name without extension and without subfolder containing description of the IES or EULUMDAT file in the subf
I have chosen Photometric now

2024-05-29 09:56 UTC, moritzstaffel commented on gdtf-spec.md
> +| LightDistributionFrom         | [Resource](#user-content-attrtype-resource )         | Optional. IES or LDT file name without extension containing the spectral data for the start of this range. |
>define new enum value for sub physical unit Type "PhotometricData". Define new enum value for PhysicalUnit "IEC" and maybe as additional for the future "EULUMDAT".

I think I would do the same think like we did for meshes with 3DS and GLTF. We allow the tool that uses this data to decide what it wants to use. IES and LDT files contain similar data, so the manufacturer can add both and the app can decide witch to use.

> all attributes, which can change light distribution like zoom will get a new sub physical with those defined new values (Annex B)

I think this is true for all Attributes. In Theorie, also Pan/Tilt could influence the light output, because of thermal requirements. I would not try to make assumptions here. 

> Beam get a new Property PhotometricData with file name

I choose Photometric for now. We can decide during our meeting. 

> All physical From and To (in channel function, channel sets, attributes...) will be changed to string

I don't see this to be good, the linear interpolation between numbers is well defined. As well for DmxProfiles. But when it is a `string`, all this behavior would need to be defined.

2024-06-13 11:22 UTC, petrvanekrobe commented on proposal/light-distribution-proposal/proposal.md
> +- When a Beam does not have `Photometric`, it will not be affected by any `Photometric` definition in the file (Allow LED rings to have no spectral data while the main light source have this and you
...Allow LED rings to have no **photometric** data...

2024-06-13 12:13 UTC, moritzstaffel commented
- [ ] Put the limitation with the DMX Channels also in the Spec

2024-06-14 07:19 UTC, AndriiVoitenko approved these changes

2024-06-20 12:05 UTC, merged