Add additional descriptions of the device
mvrdevelopment/spec pull request #193
Opened 2024-04-18 11:28 UTC by moritzstaffel

Implements #45

2024-04-25 12:44 UTC, moritzstaffel commented on gdtf-spec.md
> +| DistanceToIlluminated       | [Float](#user-content-attrtype-float )    | Minimal distance in meter from other objects; Default value: 0   |
DistanceToTarget

Minimal distance to the target of the device. For Lasers, WaterFountains, Audio and Lighting devices.

2024-05-02 12:06 UTC, petrvanekrobe commented
- Robe defined data: Min. distance from flammable materials: 1 m is a required information about distance from flammable materials based on surface temperature of the fixture's housing. This is defined in EN IEC 60598-2-17 part 2-17, section 17.6.4 - minimal distance from flammable materials of all outer surfaces of the device.


- Robe defined data: Min. distance of illuminated objects: 18 m is a required information about distance on which the fixture could make illuminated surface warmer then 90°. This is defined in EN IEC 60598-1, part 1, section 3.2.13. Often accommodated by this picture:


![image](https://github.com/mvrdevelopment/spec/assets/45997318/25be1f35-9487-42a8-b792-87b519bb4297)

2026-04-08 06:22 UTC, danielmuellerma approved these changes

2026-04-20 17:40 UTC, klinzey reviewed
Could a device have both and IEC 60529 and an IEC 62262 rating? if so Raring needs to allow for more than 1.

2026-04-20 17:51 UTC, klinzey requested changes
"Minimal distance from flammable materials ..."
should be 
"Minimum distance from flammable materials ..."

2026-04-22 05:25 UTC, petrvanekrobe commented
> Could a device have both and IEC 60529 and an IEC 62262 rating? if so Raring needs to allow for more than 1.

As these are attributes of Ratings, the Ratings is present or not. If yes, then the IKRating or IPRating might or might not be present:

```xml
<Ratings IPRating="xx" IKRating="xx" />
```

Thank you @danielmuellerma for the edit.

2026-04-22 14:48 UTC, klinzey approved these changes

2026-04-30 13:30 UTC, merged